// Independently written learning notes. These are usage explanations, not a
// claim about TOEFL frequency rankings or quotations from examination papers.
const entries = [
  ['vagrant','live as a vagrant','过流浪生活；vagrant 作名词指无固定住处的流浪者，描述人时可能带贬义'],
  ['nosy','be nosy about','爱打听……；口语用法，多指打听别人的私事'],
  ['unravel','unravel a mystery','解开谜团；也可指解开缠绕的线或使事情瓦解'],
  ['accent','have an accent','有口音；a strong accent 表示口音浓重'],
  ['instinctual','instinctual behavior','本能行为；形容由本能而非学习产生的行为'],
  ['shrivel','shrivel up','枯萎；干瘪；皱缩，常描述植物或果实'],
  ['muggy','muggy weather','闷热潮湿的天气；强调湿度高、令人不适'],
  ['outrage','public outrage','公愤；outrage at / over something 表示对某事的愤怒'],
  ['disquiet','disquiet about','对……的忧虑或不安；此处 disquiet 是名词'],
  ['interrelate','interrelate with','与……相互关联；也可以不带宾语，表示各部分相互关联'],
  ['revive','revive interest in','重新激起对……的兴趣；revive 也可不及物，表示恢复或复苏'],
  ['silversmith','a skilled silversmith','一位技艺精湛的银匠；可数名词'],
  ['scorn','treat someone with scorn','轻蔑地对待某人；with scorn 表示带着轻蔑'],
  ['disappoint','disappoint someone','使某人失望；be disappointed in / with 表示对……失望'],
  ['incessantly','talk incessantly','不停地说话；副词修饰动作，强调持续不断'],
  ['ultimatum','give someone an ultimatum','向某人发出最后通牒；也可用 issue an ultimatum'],
  ['alchemist','a medieval alchemist','一位中世纪炼金术士；用于历史或科学史语境'],
  ['appreciate','appreciate doing something','感激做某事；动词后可接名词或动名词，不用 appreciate to do'],
  ['superb','a superb performance','出色的表演或表现；superb 表示极好的'],
  ['tenant','a tenant of a building','一栋建筑物的租户；与 landlord（房东）对应'],
  ['exalt','exalt someone to a position','把某人提升到某个地位；也可表示高度赞扬，语体较正式'],
  ['deception','deliberate deception','蓄意欺骗；强调有意造成错误认识'],
  ['animate','animate beings','有生命的生物；此处 animate 是形容词，作动词则可表示使有生气'],
  ['incredulous','be incredulous at','对……感到难以置信；也可说 an incredulous look（怀疑的神情）'],
  ['mime','perform a mime','表演哑剧；作动词时指用动作模仿或表达'],
  ['gorilla','a mountain gorilla','一只山地大猩猩；gorilla 是可数名词'],
  ['cowhand','work as a cowhand','当牧牛工；cowhand 为可数名词，指照料牛群的人'],
  ['consist','consist of','由……组成；主语是整体，of 后接组成部分，不用被动语态'],
  ['distinguish','distinguish A from B','区分 A 和 B；也可用 distinguish between A and B'],
  ['differentiate','differentiate between A and B','区分 A 和 B；differentiate A from B 也表示区分'],
  ['compare','compare A with B','把 A 与 B 比较；compare A to B 也可表示把 A 比作 B'],
  ['similar','be similar to','与……相似；注意介词用 to'],
  ['familiar','be familiar with','熟悉……；人作主语用 with，事物被某人熟悉可用 be familiar to'],
  ['susceptible','be susceptible to','易受……影响或侵害；to 是介词，后接名词'],
  ['vulnerable','be vulnerable to','易遭受……；容易受到……的伤害'],
  ['account','account for','解释……的原因；占某个比例，须结合上下文判断词义'],
  ['depend','depend on','依赖……；取决于……，也可用 depend upon'],
  ['adapt','adapt to a new environment','适应新环境；adapt something for 表示把某物改编用于某目的'],
  ['benefit','benefit from','从……中受益；benefit 作名词时也可用 the benefits of'],
  ['enable','enable someone to do something','使某人能够做某事；enable + 宾语 + to do'],
  ['prevent','prevent someone from doing something','阻止某人做某事；from 后接动名词'],
  ['devote','devote time to doing something','把时间用于做某事；to 是介词，后接名词或动名词'],
  ['accustom','accustom oneself to','使自己习惯于……；be accustomed to 后接名词或动名词'],
  ['capable','be capable of doing something','有能力做某事；of 后接名词或动名词'],
  ['responsible','be responsible for','对……负责；也可表示是某事发生的原因'],
  ['aware','be aware of','意识到……；知道……，也可用 be aware that + 从句'],
  ['relevant','be relevant to','与……相关；注意介词用 to'],
  ['consistent','be consistent with','与……一致；consistent 也可以表示一贯的'],
  ['compatible','be compatible with','与……兼容；与……相容'],
  ['associate','associate A with B','把 A 与 B 联系起来；be associated with 表示与……有关'],
  ['involve','involve doing something','涉及做某事；be involved in 表示参与或卷入……'],
  ['participate','participate in','参加……；参与……，注意介词用 in'],
  ['result','result in / result from','result in 后接结果；result from 后接原因'],
  ['refer','refer to','提到……；指的是……；查阅……，依语境判断'],
  ['lead','lead to','导致……；to 是介词，后接名词或动名词'],
  ['rely','rely on','依靠……；信赖……，也可用 rely upon'],
  ['respond','respond to','回应……；对……作出反应'],
  ['object','object to doing something','反对做某事；这里 object 是动词，to 是介词'],
  ['apply','apply for a scholarship','申请奖学金；apply something to 表示把某物应用于……'],
  ['emphasize','emphasize the importance of','强调……的重要性；emphasize 后直接接宾语'],
  ['pose','pose a threat to','对……构成威胁；pose a question 表示提出问题'],
  ['impact','have an impact on','对……产生影响；注意名词短语中的冠词 an 和介词 on'],
  ['access','have access to','有机会或权利使用……；to 是介词'],
  ['attempt','make an attempt to do something','尝试做某事；attempt 作动词也可直接接 to do'],
  ['effort','make an effort to do something','努力做某事；in an effort to 表示为了努力实现……'],
  ['conclusion','draw a conclusion','得出结论；draw conclusions from 表示从……得出结论'],
  ['consensus','reach a consensus','达成共识；a consensus on 表示关于……的共识'],
  ['experiment','conduct an experiment','进行实验；experiment 作动词可用 experiment with'],
  ['research','carry out research','开展研究；名词 research 通常不可数，动词 research 可直接接宾语'],
  ['acquire','acquire knowledge','获得知识；acquire 也可接 skills、experience 等'],
  ['retain','retain information','保留或记住信息；retain 后直接接宾语'],
  ['absorb','absorb information','吸收、理解信息；也可指吸收水分或能量'],
  ['analyze','analyze data','分析数据；英式拼写为 analyse'],
  ['evidence','gather evidence','收集证据；evidence 通常不可数，可说 a piece of evidence'],
  ['hypothesis','test a hypothesis','检验假设；hypothesis 的复数为 hypotheses'],
  ['formulate','formulate a theory','提出或系统地构建一个理论；也可接 plan、policy 等'],
  ['analysis','perform an analysis','进行分析；analysis 的复数为 analyses'],
  ['arise','arise from','由……产生；arise 不及物，过去式 arose，过去分词 arisen'],
  ['allocate','allocate resources to','把资源分配给……；allocate + 资源 + to + 对象'],
  ['expenditure','expenditure on','在……方面的支出；也可用 reduce expenditure（减少支出）'],
  ['distinction','make a distinction between A and B','区分 A 和 B；draw a distinction between 也可表示作出区分'],
  ['obtain','obtain permission','获得许可；obtain 后直接接宾语'],
  ['pursue','pursue a career','从事或追求某种职业；pursue 也可接 goal、research 等'],
  ['achieve','achieve a goal','实现目标；achieve 后直接接 goal、success 等名词'],
  ['eligible','be eligible for','符合获得……的条件；也可用 be eligible to do'],
  ['qualify','qualify for','符合……的资格；qualify as 表示取得某种身份或职业资格'],
  ['tendency','have a tendency to do something','有做某事的倾向；tendency to 后接动词原形'],
  ['prone','be prone to','易于……；倾向于……，to 是介词，后接名词或动名词'],
  ['tend','tend to do something','往往做某事；倾向于做某事，to 后接动词原形'],
  ['subject','be subject to','受……影响或约束；有可能遭受……，须结合语境理解'],
  ['likely','be likely to do something','有可能做某事；也可用 It is likely that + 从句'],
  ['reluctant','be reluctant to do something','不情愿做某事；reluctant 后接 to do'],
  ['eager','be eager to do something','渴望做某事；be eager for + 名词也表示渴望……'],
];
export const preferredUsage = new Map(entries.map(([word,en,zh]) => [word, [{en,zh,type:'curated'}]]));
